export interface CryptoCard {
    id: string;
    name: string;
    provider: string;
    image: string;
    type: "metal" | "plastic";
    network: "Visa" | "Mastercard";
    region: string[];
    baseCashback: string;
    maxCashback: string;
    stakingRequired: boolean;
    stakingAmount?: string;
    issuanceFee: string;
    monthlyFee: string;
    annualFee: string;
    fxFee: string;
    atmFee: string;
    features: string[];
    mobileWallet: boolean;
    loungeAccess: boolean;
    rating: number;
    color: string;
    verificationStatus: "verified" | "verification-ongoing" | "unverified";
    description?: string;
    pros?: string[];
    cons?: string[];
    dailyLimit?: string;
    atmLimit?: string;
}

export const cryptoCards: CryptoCard[] = [
    {
        id: "1",
        name: "K Card",
        provider: "KAST",
        image: "/cards/687e25222224cbfa18ce4933_k-card-core.webp",
        type: "plastic",
        network: "Mastercard",
        region: ["Global"],
        baseCashback: "0.5%",
        maxCashback: "2%",
        stakingRequired: false,
        issuanceFee: "$10",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free up to $200",
        features: ["Rewards Points", "Instant Access", "0.25x KAST Points Boost", "Virtual Card"],
        mobileWallet: true,
        loungeAccess: false,
        rating: 4.3,
        color: "from-gray-400 to-gray-300",
        verificationStatus: "verified",
        description: "The KAST K Card is the perfect entry point into the KAST ecosystem. Get started for free with instant access to a virtual card, earn 2% rewards points on all purchases, and get 0.25x KAST points boost on your staked SOL. Standard plastic card to get you started.",
        atmLimit: "$300/month free",
        dailyLimit: "$5,000",
        pros: ["Free to get", "Instant virtual card access", "No staking required", "Earn rewards from day one"],
        cons: ["Plastic card only", "Lower points boost", "Basic tier benefits"]
    },
    {
        id: "2",
        name: "X Card",
        provider: "KAST",
        image: "/cards/687e5334d5169f3f67a3a83e_x-card-premium.webp",
        type: "metal",
        network: "Mastercard",
        region: ["Global"],
        baseCashback: "1%",
        maxCashback: "5%",
        stakingRequired: true,
        stakingAmount: "$1,000/year",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$1,000/year",
        fxFee: "0%",
        atmFee: "Free up to $1000",
        features: ["Rewards Points", "Instant Access", "0.5x KAST Points Boost", "Premium Metal Card"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.6,
        color: "from-slate-800 to-slate-600",
        verificationStatus: "verified",
        description: "The KAST X Card is the metal card for elevated living. With 5% rewards on all purchases and 0.5x KAST points boost, it's designed for those who want premium benefits. The sleek metal design makes a statement wherever you go.",
        atmLimit: "$1,000/month free",
        dailyLimit: "$15,000",
        pros: ["Premium metal design", "5% rewards", "Higher points boost", "Elevated benefits"],
        cons: ["$1,000/year fee", "Staking required for max benefits"]
    },
    {
        id: "3",
        name: "Founders Edition",
        provider: "KAST",
        image: "/cards/687e201c95962451497c3dcd_card-founders-edition.webp",
        type: "metal",
        network: "Mastercard",
        region: ["Global"],
        baseCashback: "2%",
        maxCashback: "5%",
        stakingRequired: true,
        stakingAmount: "$5,000",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free unlimited",
        features: ["Rewards Points", "VIP Concierge", "0.5x KAST Points Boost", "No Annual Fee", "Limited Edition"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.8,
        color: "from-slate-900 to-slate-700",
        verificationStatus: "verified",
        description: "The KAST Founders Edition is a strictly-limited metal card for early supporters. One-off payment of $5,000 gets you lifetime benefits with no annual fee forever, VIP concierge access to KAST's senior team, and 0.5x KAST points boost. A true collector's item.",
        atmLimit: "$2,000/month free",
        dailyLimit: "$25,000",
        pros: ["No annual fee forever", "VIP concierge access", "Limited edition collectible", "Lifetime benefits"],
        cons: ["$5,000 one-time payment", "Very limited availability"]
    },
    {
        id: "4",
        name: "Solana Gold Card",
        provider: "KAST",
        image: "/cards/687e57178f4d9881bbe2494f_solana-gold-card.webp",
        type: "metal",
        network: "Mastercard",
        region: ["Global"],
        baseCashback: "2%",
        maxCashback: "8%",
        stakingRequired: true,
        stakingAmount: "$10,000/year",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$10,000/year",
        fxFee: "0%",
        atmFee: "Free unlimited",
        features: ["8% Rewards Points", "VIP Concierge", "1x KAST Points Boost", "24K Gold Plated"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.9,
        color: "from-yellow-500 to-yellow-300",
        verificationStatus: "verified",
        description: "The KAST Solana Gold Card is the ultimate flex - a 24K gold plated card for those who want the absolute best. With 8% rewards on all purchases and 1x full KAST points boost on staked SOL, this is the pinnacle of crypto card luxury.",
        atmLimit: "Unlimited",
        dailyLimit: "Unlimited",
        pros: ["Highest 8% rewards", "24K gold plated", "Full 1x points boost", "Ultimate status symbol"],
        cons: ["$10,000/year fee", "High commitment level"]
    },
    {
        id: "5",
        name: "Bybit Card",
        provider: "Bybit",
        image: "/cards/BybitCard-2.png",
        type: "plastic",
        network: "Mastercard",
        region: ["EU", "UK"],
        baseCashback: "2%",
        maxCashback: "2%",
        stakingRequired: false,
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0.5%",
        atmFee: "Free up to €200",
        features: ["Crypto Rewards", "Global Acceptance", "Instant Card Issuance", "No Annual Fee"],
        mobileWallet: true,
        loungeAccess: false,
        rating: 4.3,
        color: "from-gray-200 to-gray-100",
        verificationStatus: "verification-ongoing",
        description: "The Bybit Card offers a straightforward way to spend your crypto with 2% cashback and no staking requirements. Backed by one of the largest crypto derivatives exchanges, it provides reliable service and global acceptance.",
        atmLimit: "$300/month free",
        dailyLimit: "$5,000",
        pros: ["No staking required", "Fast issuance", "Bybit ecosystem", "No annual fee"],
        cons: ["Verification ongoing", "Plastic only", "Basic features"]
    },
    {
        id: "6",
        name: "Obsidian Card",
        provider: "Crypto.com",
        image: "/site-bg-blue.png",
        type: "metal",
        network: "Visa",
        region: ["Global", "US", "EU", "UK", "APAC"],
        baseCashback: "5%",
        maxCashback: "8%",
        stakingRequired: true,
        stakingAmount: "$400,000",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free up to $1,000",
        features: ["Airport Lounge Access", "Private Jet Partnership", "Concierge Service", "Netflix & Spotify Rebate"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.8,
        color: "from-slate-900 to-slate-700",
        verificationStatus: "verified",
        description: "The Crypto.com Obsidian Card is the ultimate crypto card for high-net-worth individuals. With industry-leading 8% cashback on all purchases and exclusive lifestyle benefits, it represents the pinnacle of crypto card offerings.",
        atmLimit: "Unlimited",
        dailyLimit: "Unlimited",
        pros: ["Highest cashback rate at 8%", "Premium metal design", "No annual fee", "Comprehensive travel benefits"],
        cons: ["Requires $400K CRO stake", "180-day lock-up period"]
    },
    {
        id: "7",
        name: "Icy White Card",
        provider: "Crypto.com",
        image: "/site-bg-final.jpg",
        type: "metal",
        network: "Visa",
        region: ["Global", "US", "EU", "UK", "APAC"],
        baseCashback: "3%",
        maxCashback: "5%",
        stakingRequired: true,
        stakingAmount: "$40,000",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free up to $1,000",
        features: ["Airport Lounge Access", "Netflix & Spotify Rebate", "10% Staking Rewards"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.7,
        color: "from-blue-100 to-blue-50",
        verificationStatus: "verified",
        description: "The Icy White Card offers premium benefits at a more accessible staking tier. With 5% cashback, airport lounge access, and multiple subscription rebates, it's perfect for serious crypto enthusiasts.",
        atmLimit: "$1,000/month free",
        dailyLimit: "$25,000",
        pros: ["5% cashback is excellent", "Beautiful frosted design", "Airport lounge access"],
        cons: ["$40K stake required", "180-day lock-up period"]
    },
    {
        id: "8",
        name: "Royal Indigo Card",
        provider: "Crypto.com",
        image: "/hero-bg.jpg",
        type: "metal",
        network: "Visa",
        region: ["Global", "US", "EU", "UK", "APAC"],
        baseCashback: "2%",
        maxCashback: "3%",
        stakingRequired: true,
        stakingAmount: "$4,000",
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free up to $800",
        features: ["Netflix & Spotify Rebate", "Airport Lounge Access", "Free ATM Withdrawals"],
        mobileWallet: true,
        loungeAccess: true,
        rating: 4.6,
        color: "from-indigo-600 to-purple-600",
        verificationStatus: "verified",
        description: "The Royal Indigo Card is the sweet spot for most crypto users. It offers a solid 3% cashback, streaming rebates, and lounge access at a reasonable staking requirement.",
        atmLimit: "$800/month free",
        dailyLimit: "$15,000",
        pros: ["Good balance of benefits vs stake", "Metal card", "Lounge access included"],
        cons: ["Lower cashback than higher tiers", "Stake required"]
    },
    {
        id: "9",
        name: "Nexo Card",
        provider: "Nexo",
        image: "/site-bg-blue.png",
        type: "metal",
        network: "Mastercard",
        region: ["EU", "UK"],
        baseCashback: "0.5%",
        maxCashback: "2%",
        stakingRequired: false,
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "0%",
        atmFee: "Free up to €10,000",
        features: ["No Staking Required", "Crypto-backed Credit", "Instant Approval", "Premium Support"],
        mobileWallet: true,
        loungeAccess: false,
        rating: 4.5,
        color: "from-blue-600 to-blue-800",
        verificationStatus: "verified",
        description: "The Nexo Card stands out by offering crypto-backed credit without requiring any staking. Simply use your crypto as collateral and spend without selling.",
        atmLimit: "$500/month free",
        dailyLimit: "$10,000",
        pros: ["No staking requirement", "Crypto-backed credit line", "Instant approval"],
        cons: ["Lower base cashback", "Interest on credit line"]
    },
    {
        id: "10",
        name: "Coinbase Card",
        provider: "Coinbase",
        image: "/site-bg-final.jpg",
        type: "plastic",
        network: "Visa",
        region: ["US"],
        baseCashback: "1%",
        maxCashback: "4%",
        stakingRequired: false,
        issuanceFee: "$0",
        monthlyFee: "$0",
        annualFee: "$0",
        fxFee: "2.49%",
        atmFee: "Free at Coinbase ATMs",
        features: ["Choose Your Crypto Rewards", "No Annual Fee", "Google Pay & Apple Pay", "Instant Spending"],
        mobileWallet: true,
        loungeAccess: false,
        rating: 4.2,
        color: "from-blue-500 to-indigo-600",
        verificationStatus: "verification-ongoing",
        description: "The Coinbase Card lets you spend any crypto and choose which crypto you want as rewards. Backed by one of the most trusted names in crypto.",
        atmLimit: "$500/month free",
        dailyLimit: "$7,500",
        pros: ["Choose your reward crypto", "Spend any crypto", "Trusted platform"],
        cons: ["FX fees apply", "Plastic only"]
    }
];
